repos:
  - repo: local
    hooks:
      - id: use rustfmt to format code
        name: rustfmt
        entry: cargo fmt -- --check
        language: rust
        types: [rust]
      - id: use clippy to lint code
        name: clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: rust
        types: [rust]
        pass_filenames: false
      - id: check for security vulnerabilities
        name: cargo-audit
        entry: cargo audit
        language: rust
        types: [rust]
        pass_filenames: false