name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2 and SDL2_ttf
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-ttf-dev
    - name: Install cargo tools
      run: cargo install cargo-audit cargo-deny cargo-tarpaulin cargo-chef
    - name: Security audit
      run: cargo audit
    - name: Deny check
      run: cargo deny check
    - name: Run tests
      run: cargo tarpaulin
    - name: Build project using cargo chef
      run: |
        cargo chef prepare --recipe-path recipe.json
        cargo chef cook --release --recipe-path recipe.json
        cargo build --release
